export const SHOW_ALL_IMAGE_REQUEST = "SHOW_ALL_IMAGE_REQUEST";
export const SHOW_ALL_IMAGE_SUCCESS = "SHOW_ALL_IMAGE_SUCCESS";
export const SHOW_ALL_IMAGE_FAIL = "SHOW_ALL_IMAGE_FAIL";
export const ADD_IMAGE_REQUEST = "ADD_IMAGE_REQUEST";
export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_FAIL = "ADD_IMAGE_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ADD_IMAGE_RESET = "ADD_IMAGE_RESET";
export const IMAGE_REQUEST = "IMAGE_REQUEST";
export const IMAGE_SUCCESS = "IMAGE_SUCCESS";
export const IMAGE_FAIL = "IMAGE_FAIL";
export const EDIT_IMAGE_REQUEST = "EDIT_IMAGE_REQUEST";
export const EDIT_IMAGE_SUCCESS = "EDIT_IMAGE_SUCCESS";
export const EDIT_IMAGE_FAIL = "EDIT_IMAGE_FAIL";
export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAIL = "DELETE_IMAGE_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOAD_REQUEST = "LOAD_REQUEST";
export const LOAD_SUCCESS = "LOAD_SUCCESS";
export const LOAD_FAIL = "LOAD_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";
export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
